import '../globals.css';
import type { Metadata } from 'next';
import React from 'react';
import { ShortcutProvider } from '../../src/components/system/ShortcutProvider';


export const metadata: Metadata = {
  title: 'FilaCero',
  description: 'Generated by create next app'
};

// Nota: En layouts anidados no debemos renderizar <html> ni <body>.
export default function PosLayout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <ShortcutProvider>
        {children}
      </ShortcutProvider>
    </div>
  );
}
