services:
  filacerofrontend:
    image: filacerofrontend
    build:
      context: Frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  mongo:
    image: mongo:7
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
volumes:
  mongo_data:
