import './globals.css';
import type { Metadata } from 'next';
import React from 'react';
import { UserProvider } from '../src/state/userStore';
import ClientSettingsApplier from '../src/components/ClientSettingsApplier';
import LanguageInitializer from '../src/components/LanguageInitializer';
import { ConfirmProvider } from '../src/components/system/ConfirmProvider';


export const metadata: Metadata = {
  title: 'FilaCero',
  description: 'Generated by create next app',
  // Establece metadataBase para URLs absolutas (OpenGraph/Twitter), evita warning en build
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000')
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body>
        <UserProvider>
          <LanguageInitializer />
          <ClientSettingsApplier />
          <ConfirmProvider>
            {children}
          </ConfirmProvider>
        </UserProvider>
      </body>
    </html>
  );
}
