import './globals.css';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import React from 'react';
import { UserProvider } from '../src/state/userStore'; // Ajusta la ruta

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'FilaCero',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}><UserProvider>{children}</UserProvider></body>
    </html>
  );
}
